# Generated by Django 2.2.6 on 2021-09-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='url_height', upload_to='img/', width_field='url_width')),
                ('url_height', models.IntegerField(editable=False)),
                ('url_width', models.IntegerField(editable=False)),
            ],
        ),
    ]
