# Generated by Django 2.2.6 on 2021-09-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
