# Generated by Django 2.2.6 on 2021-09-30 03:38

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210928_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=stdimage.models.StdImageField(upload_to='img/'),
        ),
    ]
