# Generated by Django 2.2.6 on 2021-10-04 01:31

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20210930_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='img/'),
        ),
    ]
